### ISSUE TITLE
TypeError: Cannot read property 'annotations' of undefined

### ISSUE THREAD

**Issue by wannadream** [davideast/ng2do#21]
I am not sure if I did something wrong. Error log below.

<pre><code>
TypeError: Cannot read property 'annotations' of undefined

TypeError: Cannot read property 'annotations' of undefined
    at ReflectionCapabilities.$**export.annotations (http://localhost:3456/quickstart/angular2/src/reflection/reflection_capabilities.js:81:40)
    at Reflector.$__export.annotations (http://localhost:3456/quickstart/angular2/src/reflection/reflector.js:81:50)
    at DirectiveMetadataReader.$__export.read (http://localhost:3456/quickstart/angular2/src/core/compiler/directive_metadata_reader.js:31:41)
    at http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:127:35
    at Array.map (native)
    at Function.$__export.map (http://localhost:3456/quickstart/angular2/src/facade/collection.js:172:26)
    at Compiler.$__export.createSteps (http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:126:43)
    at Compiler.$__export._compileTemplate (http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:164:53)
    at http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:154:29
    at Zone.run (http://localhost:3456/quickstart/dist/es6-shim.js:29889:19)
:3456/quickstart/angular2/src/core/application.js:119 Uncaught (in promise) TypeError: Cannot read property 'annotations' of undefinedmessage: "Cannot read property 'annotations' of undefined"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto**: Error

</pre></code>

**Comment by CWSpear** [comment]
Getting this error, too, following the instructions on the main page!

**Comment by dhensche** [comment]
+1

**Comment by davideast** [comment]
Angular 2 changes daily, which causes crazy errors like this. We're in the process of changing everything to use TypeScript. TypeScript should make everything easier to build. This should be resolved soon. Sorry everyone!

**Comment by wannadream** [comment]
Thanks, David. I saw lots of documentation is being updated on AngularJS 2 website. Looking forward to using it asap.

**Comment by dylanb** [comment]
If you want to fix the issues, change:

@Template -> @View
inline ->template
events -> hostListeners

A bunch of the imports have moved

EventEmitter is no longer injected, you have to instantiate it with new EventEmitter();

**Comment by danielstern** [comment]
+1

**Comment by mhrisse** [comment]
PRs welcome! :)

**Comment by davideast** [comment]
I'll have this updated soon.
